### PR TITLE
Convert convertible types to string on setBody()

### PR DESCRIPTION
**Pull request by kelunik**
Two separate methods would really have been cleaner, as that would have allowed people to use strict types if they prefer.

### CODE REVIEW

**Comment by trowski** [comment]
Perhaps, but then the constructor probably would still have been mixed, so then we'd need type-checking logic there.

This method matches better with how we handle mixed types for header values, so :+1:.

**Comment by trowski** [comment]
Giving this more thought, I assume this is largely to accommodate objects with a `__toString()` method, which perhaps we should explicitly check for rather than relying on casting here. Passing a number or bool for the body is certainly a coding error, whereas for headers it is not.

**Comment by kelunik** [comment]
I've run into this because I passed an integer as body, not because of toString. It was a simple visitor counter.

**Comment by kelunik** [comment]
@trowski Should we merge this or not?

**Pull request merged**
